<?php
namespace App\Http\Controllers\SecondLife;
use App\Http\Controllers\Controller; use App\Models\PaymentProfile; use App\Models\SecondLifeOrder; use App\Services\Payments\DirectSbpOrderService; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Marvel\Database\Models\Product;
class OrderController extends Controller {
 public function __construct(private DirectSbpOrderService $service){}
 public function store(Request $r){$d=$r->validate(['product_id'=>['required','integer','exists:products,id']]);$o=$this->service->createOrder($r->user(),Product::findOrFail($d['product_id']));return response()->json(['order'=>$this->resource($o,$r)],201);}
 public function paymentOptions(int $productId){$p=Product::with('shop.balance')->findOrFail($productId);$base=(float)($p->sale_price??$p->price??$p->min_price??0);$rate=max(0,(float)($p->shop?->balance?->admin_commission_rate??0));$sellerId=$p->shop?->owner_id??$p->shop?->user_id??$p->seller_id??$p->user_id;$sbpAvailable=$sellerId&&PaymentProfile::active()->where('user_id',$sellerId)->whereNotNull('receiver_name')->whereNotNull('phone')->whereNotNull('bank_name')->exists();return ['direct_sbp'=>['available'=>$sbpAvailable,'price'=>$base,'commission_rate'=>0],'site_payment'=>['available'=>true,'price'=>round($base*(1+$rate/100),2),'commission_rate'=>$rate]];}
 public function show(Request $r,string $publicId){$o=$this->find($publicId);$this->access($r,$o);return ['order'=>$this->resource($o,$r)];}
 public function markPaid(Request $r,string $publicId){$o=$this->find($publicId);$d=$r->validate(['comment'=>['nullable','string','max:2000'],'screenshot'=>['nullable','image','mimes:jpg,jpeg,png,webp','max:10240']]);if($r->hasFile('screenshot'))$d['screenshot_path']=$r->file('screenshot')->store('private/payment-proofs');$c=$this->service->markPaidByBuyer($o,$r->user(),$d);return ['status'=>'buyer_marked_paid','message'=>'Ожидаем подтверждения продавца','confirmation'=>$c];}
 public function confirmPayment(Request $r,string $publicId){$o=$this->find($publicId);$this->service->confirmPaymentBySeller($o,$r->user());return ['status'=>'paid','payment_status'=>'seller_confirmed_paid'];}
 public function rejectPayment(Request $r,string $publicId){$d=$r->validate(['reason'=>['required','string','max:2000']]);$o=$this->find($publicId);$this->service->rejectPaymentBySeller($o,$r->user(),$d['reason']);return $this->resource($o->fresh(),$r);}
 public function cancel(Request $r,string $publicId){$o=$this->find($publicId);$this->service->cancel($o,$r->user());return $this->resource($o->fresh(),$r);}
 public function openDispute(Request $r,string $publicId){$d=$r->validate(['reason'=>['required','string','max:2000']]);$o=$this->find($publicId);$this->service->openDispute($o,$r->user(),$d['reason']);return $this->resource($o->fresh(),$r);}
 public function proof(Request $r,string $publicId,int $confirmation){$o=$this->find($publicId);$this->access($r,$o);$c=$o->confirmations()->findOrFail($confirmation);abort_unless($c->screenshot_path,404);return Storage::download($c->screenshot_path);}
 public function qr(Request $r,string $publicId){$o=$this->find($publicId);$this->access($r,$o);abort_unless($o->paymentDetails?->uploaded_qr_path,404);return Storage::download($o->paymentDetails->uploaded_qr_path);}
 private function find(string $id):SecondLifeOrder{return SecondLifeOrder::where('public_id',$id)->orWhere('id',$id)->with(['paymentDetails','confirmations','events','product','buyer','seller'])->firstOrFail();}
 private function access(Request $r,SecondLifeOrder $o):void{abort_unless(in_array((int)$r->user()->id,[(int)$o->buyer_id,(int)$o->seller_id],true)||$r->user()->hasPermissionTo('super_admin'),403);}
 private function resource(SecondLifeOrder $o,Request $r):array{$o->loadMissing(['paymentDetails','confirmations','events','product','buyer','seller']);$a=$o->toArray();if(!in_array((int)$r->user()->id,[(int)$o->buyer_id,(int)$o->seller_id],true))unset($a['payment_details']['phone']);return $a;}
}
