<?php
namespace App\Services\Payments;
use App\Models\{OrderEvent,OrderPaymentDetail,PaymentConfirmation,SecondLifeOrder}; use App\Services\Orders\OrderStateService; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException; use Marvel\Database\Models\{Product,Shop,User};
class DirectSbpOrderService {
 public function __construct(private PaymentProfileService $profiles,private OrderStateService $states){}
 public function createOrder(User $buyer,Product $product):SecondLifeOrder{return DB::transaction(function()use($buyer,$product){$product=Product::whereKey($product->id)->lockForUpdate()->firstOrFail();if($product->reserved_until&&$product->reserved_until->isFuture())throw ValidationException::withMessages(['product'=>'Товар временно зарезервирован']);$seller=User::findOrFail($this->sellerId($product));if((int)$seller->id===(int)$buyer->id)throw ValidationException::withMessages(['product'=>'Нельзя купить собственный товар']);$profile=$this->profiles->getDefaultProfile($seller);if(!$profile)throw ValidationException::withMessages(['payment_profile'=>'У продавца нет активного профиля СБП']);$order=SecondLifeOrder::create(['public_id'=>'SL-'.now()->format('Ymd').'-'.strtoupper(substr(bin2hex(random_bytes(4)),0,8)),'buyer_id'=>$buyer->id,'seller_id'=>$seller->id,'product_id'=>$product->id,'payment_profile_id'=>$profile->id,'price'=>$product->sale_price??$product->price??$product->min_price??0,'platform_fee'=>0,'currency'=>'RUB','payment_method'=>'direct_sbp','payment_status'=>'waiting_payment','order_status'=>'waiting_payment','reserved_until'=>now()->addMinutes(30)]);OrderPaymentDetail::create(['order_id'=>$order->id,'receiver_name'=>$profile->receiver_name,'phone'=>$profile->phone,'bank_name'=>$profile->bank_name,'bank_code'=>$profile->bank_code,'uploaded_qr_path'=>$profile->uploaded_qr_path,'payment_link'=>$profile->payment_link]);$product->forceFill(['reserved_at'=>now(),'reserved_until'=>$order->reserved_until,'reserved_by_order_id'=>$order->id])->save();$this->event($order,$buyer,'order_created');$this->event($order,$buyer,'product_reserved');return $order->load(['paymentDetails','product','seller']);});}
 public function markPaidByBuyer(SecondLifeOrder $o,User $u,array $d):PaymentConfirmation{abort_unless((int)$o->buyer_id===(int)$u->id,403);return DB::transaction(function()use($o,$u,$d){$this->states->transition($o,'buyer_marked_paid','buyer_marked_paid');$c=PaymentConfirmation::create(['order_id'=>$o->id,'buyer_id'=>$u->id,'amount'=>$o->price,'comment'=>$d['comment']??null,'screenshot_path'=>$d['screenshot_path']??null,'status'=>'submitted','submitted_at'=>now()]);$o->update(['buyer_marked_paid_at'=>now()]);$this->event($o,$u,'buyer_marked_paid');return $c;});}
 public function confirmPaymentBySeller(SecondLifeOrder $o,User $u):void{abort_unless((int)$o->seller_id===(int)$u->id,403);DB::transaction(function()use($o,$u){$this->states->transition($o,'paid','seller_confirmed_paid');$o->update(['seller_confirmed_paid_at'=>now(),'seller_confirmed_at'=>now()]);$o->confirmations()->latest()->first()?->update(['status'=>'confirmed','reviewed_at'=>now(),'reviewed_by'=>$u->id]);$this->event($o,$u,'seller_confirmed_payment');});}
 public function rejectPaymentBySeller(SecondLifeOrder $o,User $u,string $reason):void{abort_unless((int)$o->seller_id===(int)$u->id,403);DB::transaction(function()use($o,$u,$reason){$this->states->transition($o,'payment_not_found','payment_not_found');$o->update(['payment_rejected_at'=>now(),'dispute_reason'=>$reason]);$o->confirmations()->latest()->first()?->update(['status'=>'rejected','reviewed_at'=>now(),'reviewed_by'=>$u->id]);$this->event($o,$u,'seller_rejected_payment',['reason'=>$reason]);});}
 public function openDispute(SecondLifeOrder $o,User $u,string $reason):void{abort_unless(in_array((int)$u->id,[(int)$o->buyer_id,(int)$o->seller_id],true),403);DB::transaction(function()use($o,$u,$reason){$o->update(['order_status'=>'disputed','payment_status'=>'disputed','dispute_reason'=>$reason]);$this->event($o,$u,'payment_dispute_opened',['reason'=>$reason]);});}
 public function cancel(SecondLifeOrder $o,?User $u=null):void{if($u)abort_unless(in_array((int)$u->id,[(int)$o->buyer_id,(int)$o->seller_id],true),403);if($o->payment_status==='seller_confirmed_paid')throw ValidationException::withMessages(['order'=>'Оплаченный заказ нельзя отменить']);DB::transaction(function()use($o,$u){$o->update(['order_status'=>'cancelled','payment_status'=>'cancelled','cancelled_at'=>now()]);Product::whereKey($o->product_id)->where('reserved_by_order_id',$o->id)->update(['reserved_at'=>null,'reserved_until'=>null,'reserved_by_order_id'=>null]);$this->event($o,$u,'order_cancelled');});}
 public function cancelExpiredReservation(SecondLifeOrder $o):void{if($o->reserved_until?->isPast()&&in_array($o->order_status,['reserved','waiting_payment'],true))$this->cancel($o);}
 private function event(SecondLifeOrder $o,?User $u,string $type,array $payload=[]):void{OrderEvent::create(['order_id'=>$o->id,'user_id'=>$u?->id,'event_type'=>$type,'payload'=>$payload?:null]);}
 private function sellerId(Product $p):int{if($p->seller_id??null)return(int)$p->seller_id;if($p->user_id??null)return(int)$p->user_id;$s=Shop::find($p->shop_id);return(int)($s?->owner_id?:$s?->user_id);}
}
